#!/bin/sh

BASE_DIR=~/.config/develop
BIN_DIR=$BASE_DIR/bin
INSTALL_DIR=/usr/local

rm -rf $BASE_DIR
git clone git@github.com:tk-shirasaka/develop $BASE_DIR

ln -s $BASE_DIR/bin/develop $INSTALL_DIR/bin/develop
