vim.keymap.set('n', '<cr>', "denite#do_map('do_action')", { silent = true, expr = true, buffer = 0 })
vim.keymap.set('n', '<tab>', "denite#do_map('choose_action')", { silent = true, expr = true, buffer = 0 })
vim.keymap.set('n', '<c-l>', "denite#do_map('redraw')", { silent = true, expr = true, buffer = 0 })
vim.keymap.set('n', '<esc>', "denite#do_map('quit')", { silent = true, expr = true, buffer = 0 })
vim.keymap.set('n', '<space>', "denite#do_map('toggle_select').'j'", { silent = true, expr = true, buffer = 0 })
vim.keymap.set('n', '*', "denite#do_map('toggle_select_all')", { silent = true, expr = true, buffer = 0 })
vim.keymap.set('n', 'i', "denite#do_map('open_filter_buffer')", { silent = true, expr = true, buffer = 0 })
vim.keymap.set('n', 'u', "denite#do_map('restore_sources')", { silent = true, expr = true, buffer = 0 })
vim.keymap.set('n', 'p', "denite#do_map('toggle_auto_action', 'preview')", { silent = true, expr = true, buffer = 0 })
vim.keymap.set('n', '-', "denite#do_map('move_up_path')", { silent = true, expr = true, buffer = 0 })
