vim.api.nvim_buf_set_keymap(0, 'n', '<cr>', "denite#do_map('do_action')", { noremap = true, silent = true, expr = true })
vim.api.nvim_buf_set_keymap(0, 'n', '<tab>', "denite#do_map('choose_action')", { noremap = true, silent = true, expr = true })
vim.api.nvim_buf_set_keymap(0, 'n', '<c-l>', "denite#do_map('redraw')", { noremap = true, silent = true, expr = true })
vim.api.nvim_buf_set_keymap(0, 'n', '<esc>', "denite#do_map('quit')", { noremap = true, silent = true, expr = true })
vim.api.nvim_buf_set_keymap(0, 'n', '<space>', "denite#do_map('toggle_select').'j'", { noremap = true, silent = true, expr = true })
vim.api.nvim_buf_set_keymap(0, 'n', '*', "denite#do_map('toggle_select_all')", { noremap = true, silent = true, expr = true })
vim.api.nvim_buf_set_keymap(0, 'n', 'i', "denite#do_map('open_filter_buffer')", { noremap = true, silent = true, expr = true })
vim.api.nvim_buf_set_keymap(0, 'n', 'u', "denite#do_map('restore_sources')", { noremap = true, silent = true, expr = true })
vim.api.nvim_buf_set_keymap(0, 'n', 'p', "denite#do_map('toggle_auto_action', 'preview')", { noremap = true, silent = true, expr = true })
vim.api.nvim_buf_set_keymap(0, 'n', '-', "denite#do_map('move_up_path')", { noremap = true, silent = true, expr = true })
